# Do not edit. Generated by the configure script.
export PATH:=/opt/ssd/jetson_rb_webengine/dev/engine_src_github/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.9
PREFIX=/usr/local
